backend:
  name: github
  repo: 21stAmendmentBrewery/21A-marketing # Replace with your repo
  branch: master

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images"
