name = "_underscore"
license = "MIT"
licenselink = "https://github.com/kungfukoala/_underscore/LICENSE.md"
description = "A basic theme created on top of Victor Hugo"
homepage = "https://github.com/kungfukoala/_underscore"
tags = []
features = ["responsive", "multilingual", "i18n"]
min_version = 0.1

[author]
  name = "Benjamin Kinzer"
  homepage = "https://github.com/kungfukoala"
