name = "_underscore"
license = "MIT"
licenselink = "https://github.com/Xzya/hugo-bootstrap/blob/master/LICENSE.md"
description = "A basic theme created for Victor Hugo"
homepage = "https://github.com/Xzya/hugo-bootstrap"
tags = []
features = ["responsive", "multilingual", "i18n"]
min_version = 0.1

[author]
  name = "Benjamin Kinzer"
  homepage = "https://github.com/kungfukoala"
